import express from 'express';
import {validateDetails,withDetails} from './project-details.js';
import helmet from 'helmet';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, scryptSync, timingSafeEqual, createHash } from 'node:crypto';
import { mkdirSync, existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const data=process.env.DATA_DIR || path.join(root,'data'); mkdirSync(data,{recursive:true});
const uploads=process.env.UPLOADS_DIR || path.join(root,'public/uploads');mkdirSync(uploads,{recursive:true});
const db=new DatabaseSync(path.join(data,'catalogue.sqlite'));
db.exec('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS users (username TEXT PRIMARY KEY, salt TEXT, hash TEXT); CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, expires INTEGER); CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, type TEXT NOT NULL, material TEXT NOT NULL, description TEXT NOT NULL, image TEXT NOT NULL, published INTEGER NOT NULL DEFAULT 1);');
if(!db.prepare('PRAGMA table_info(items)').all().some(c=>c.name==='details'))db.exec("ALTER TABLE items ADD COLUMN details TEXT NOT NULL DEFAULT '{}'");
if(!db.prepare('SELECT username FROM users LIMIT 1').get()){
 const username=process.env.ADMIN_USER||'admin',password=process.env.ADMIN_PASSWORD||randomBytes(15).toString('base64url'),salt=randomBytes(16).toString('hex');
 db.prepare('INSERT INTO users VALUES (?,?,?)').run(username,salt,scryptSync(password,salt,64).toString('hex'));
 writeFileSync(path.join(data,'acesso-local.txt'),`Utilizador: ${username}\nPalavra-passe: ${password}\n`); 
 const insert=db.prepare('INSERT INTO items (title,type,material,description,image) VALUES (?,?,?,?,?)');
 for(const [title,type,material,image] of [['Lorem ipsum','produto','Mármore','marble.jpg'],['Dolor sit amet','produto','Calcário','stone.jpg'],['Consectetur elit','produto','Granito','marble.jpg'],['Lorem residence','projeto','Mármore','interior.jpg'],['Dolor studio','projeto','Calcário','interior.jpg'],['Amet exterior','projeto','Granito','stone.jpg']]) insert.run(title,type,material,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',`/assets/${image}`);
}
const app=express();if(process.env.TRUST_PROXY==='1')app.set('trust proxy',1); app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'7mb'}));
app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)){const origin=req.get('origin');if(origin&&origin!==(process.env.APP_ORIGIN||`${req.protocol}://${req.get('host')}`))return res.status(403).json({error:'Origem não autorizada.'});}next();});
const digest=t=>createHash('sha256').update(t).digest('hex');
function auth(req,res,next){const token=(req.headers.cookie||'').split('; ').find(c=>c.startsWith('is_session='))?.slice(11);if(!token||!db.prepare('SELECT token FROM sessions WHERE token=? AND expires>?').get(digest(token),Date.now()))return res.status(401).json({error:'Inicie sessão para continuar.'});next();}
const attempts=new Map();
app.post('/api/login',(req,res)=>{const key=req.ip;let a=attempts.get(key);if(a&&a.until<Date.now()){attempts.delete(key);a=null;}if(a?.count>=8)return res.status(429).json({error:'Demasiadas tentativas. Tente novamente dentro de 15 minutos.'});const {username,password}=req.body||{};if(typeof username!=='string'||typeof password!=='string'||password.length>200)return res.status(400).json({error:'Dados de acesso inválidos.'});const user=db.prepare('SELECT * FROM users WHERE username=?').get(username);const hash=scryptSync(password,user?.salt||'invalid-salt',64);if(!user||!timingSafeEqual(hash,Buffer.from(user.hash,'hex'))){attempts.set(key,{count:(a?.count||0)+1,until:a?.until||Date.now()+900000});return res.status(401).json({error:'Utilizador ou palavra-passe incorretos.'});}attempts.delete(key);const token=randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES (?,?)').run(digest(token),Date.now()+8*3600000);res.cookie('is_session',token,{httpOnly:true,sameSite:'strict',secure:req.secure,maxAge:8*3600000,path:'/'});res.json({ok:true});});
app.get('/api/session',auth,(req,res)=>res.json({ok:true}));
app.post('/api/logout',(req,res)=>{const token=(req.headers.cookie||'').split('; ').find(c=>c.startsWith('is_session='))?.slice(11);if(token)db.prepare('DELETE FROM sessions WHERE token=?').run(digest(token));res.clearCookie('is_session',{path:'/'});res.json({ok:true});});
app.get('/api/catalogue',(req,res)=>res.json(db.prepare('SELECT * FROM items WHERE published=1 ORDER BY id DESC').all().map(withDetails)));
app.get('/api/admin/catalogue',auth,(req,res)=>res.json(db.prepare('SELECT * FROM items ORDER BY id DESC').all().map(withDetails)));
function validate(body){const {title,type,material,description,image,published}=body||{};if(typeof title!=='string'||!title.trim()||title.length>100||!['produto','projeto'].includes(type)||typeof material!=='string'||!material.trim()||material.length>80||typeof description!=='string'||description.length>3000||typeof image!=='string'||image.length>200||!/^\/(assets|uploads)\/[a-zA-Z0-9_.-]+\.(jpg|jpeg|png|webp)$/.test(image)||typeof published!=='boolean')return null;const details=validateDetails(body);if(details===null)return null;return [title.trim(),type,material.trim(),description,image,published?1:0,details];}
app.post('/api/admin/catalogue',auth,(req,res)=>{const values=validate(req.body);if(!values)return res.status(400).json({error:'Verifique os campos e a imagem.'});const result=db.prepare('INSERT INTO items (title,type,material,description,image,published,details) VALUES (?,?,?,?,?,?,?)').run(...values);res.status(201).json({id:Number(result.lastInsertRowid)});});
app.put('/api/admin/catalogue/:id',auth,(req,res)=>{const values=validate(req.body);if(!values)return res.status(400).json({error:'Verifique os campos e a imagem.'});const r=db.prepare('UPDATE items SET title=?,type=?,material=?,description=?,image=?,published=?,details=? WHERE id=?').run(...values,req.params.id);if(!r.changes)return res.status(404).json({error:'Entrada não encontrada.'});res.json({ok:true});});
app.delete('/api/admin/catalogue/:id',auth,(req,res)=>{const r=db.prepare('DELETE FROM items WHERE id=?').run(req.params.id);if(!r.changes)return res.status(404).json({error:'Entrada não encontrada.'});res.json({ok:true});});
app.post('/api/admin/upload',auth,(req,res)=>{const value=req.body?.data;if(typeof value!=='string')return res.status(400).json({error:'Imagem inválida.'});const match=value.match(/^data:image\/(jpeg|png|webp);base64,([A-Za-z0-9+/=]+)$/);if(!match)return res.status(400).json({error:'Escolha uma imagem JPG, PNG ou WebP.'});const bytes=Buffer.from(match[2],'base64');const valid=match[1]==='jpeg'?bytes[0]===255&&bytes[1]===216:match[1]==='png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP';if(!valid||bytes.length>5*1024*1024)return res.status(400).json({error:'Imagem inválida ou superior a 5 MB.'});mkdirSync(uploads,{recursive:true});const name=`${randomBytes(16).toString('hex')}.${match[1]}`;writeFileSync(path.join(uploads,name),bytes);res.json({image:`/uploads/${name}`});});
app.get('/api/health',(req,res)=>{db.prepare('SELECT 1').get();res.json({ok:true});});
app.use('/api',(req,res)=>res.status(404).json({error:'Recurso não encontrado.'}));
app.use('/uploads',express.static(uploads));
if(process.argv.includes('--production')){if(!existsSync(path.join(root,'dist/index.html')))throw new Error('Execute npm run build primeiro.');app.use(express.static(path.join(root,'dist')));app.get('/{*path}',(req,res)=>res.sendFile(path.join(root,'dist/index.html')));}else{const {createServer}=await import('vite');const vite=await createServer({root,server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}
app.use((err,req,res,next)=>{console.error(err.message);res.status(err.status||500).json({error:err.status===413?'A imagem excede o limite permitido.':'Não foi possível concluir. Tente novamente.'});});
const port=Number(process.env.PORT||3000);app.listen(port,process.env.HOST||'127.0.0.1',()=>console.log(`Infinity Stone: http://localhost:${port}`));
