import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
const errors=[];
const desktop=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});
desktop.on('pageerror',e=>errors.push(e.message));
await desktop.goto('http://localhost:3000');await desktop.waitForLoadState('networkidle');
await desktop.screenshot({path:'.impeccable/review/motion-desktop.png',fullPage:true});
await desktop.locator('.depth-gallery').scrollIntoViewIfNeeded();
const title=desktop.locator('.depth-copy h2');const initial=await title.textContent();
await desktop.getByRole('button',{name:'Seguinte',exact:true}).click();
assert.notEqual(await title.textContent(),initial);
const frames=await desktop.evaluate(()=>{
  const animations=document.querySelector('.depth-gallery').getAnimations({subtree:true});
  const data=animations.map(a=>({duration:a.effect.getTiming().duration,frames:a.effect.getKeyframes()}));
  animations.forEach(a=>{a.pause();a.currentTime=95});return data;
});
assert.ok(frames.length>0,'Gallery must animate for pointer input');
assert.ok(frames.every(a=>a.duration<=220),'Gallery animations must be brief');
await desktop.screenshot({path:'.impeccable/review/motion-gallery-midpoint.png'});
await desktop.evaluate(()=>document.querySelector('.depth-gallery').getAnimations({subtree:true}).forEach(a=>a.play()));
// Rapid reversals must update immediately and leave no retiring image behind.
await desktop.evaluate(()=>{const next=document.querySelector('.gallery-controls button:last-child');const prev=document.querySelector('.gallery-controls button:first-child');for(let i=0;i<8;i++){next.click();prev.click()}});
for(let i=0;i<6;i++){
  await desktop.evaluate(next=>document.querySelector(next?'.gallery-controls button:last-child':'.gallery-controls button:first-child').click(),i%2===0);
  await desktop.waitForTimeout(30);
}
await desktop.waitForTimeout(300);
assert.equal(await desktop.locator('.gallery-image-previous').count(),0);
assert.equal(await desktop.locator('.depth-main').getAttribute('aria-label'),'Ver '+await title.textContent());
await desktop.getByRole('button',{name:'Seguinte',exact:true}).focus();
await desktop.keyboard.press('Enter');
assert.equal(await desktop.evaluate(()=>document.querySelector('.depth-gallery').getAnimations({subtree:true}).length),0,'Keyboard changes are immediate');
await desktop.getByRole('button',{name:'Seguinte',exact:true}).click();
await desktop.emulateMedia({reducedMotion:'reduce'});
await desktop.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
assert.equal(await desktop.evaluate(()=>document.querySelector('.depth-gallery').getAnimations({subtree:true}).length),0,'Preference changes cancel in-flight animations');
await desktop.getByRole('button',{name:'Seguinte',exact:true}).click();
assert.equal(await desktop.evaluate(()=>document.querySelector('.depth-gallery').getAnimations({subtree:true}).length),0);
await desktop.locator('.depth-main').hover();
assert.equal(await desktop.locator('.depth-main').evaluate(e=>getComputedStyle(e).transform),'none');
await desktop.goto('http://localhost:3000/servicos');
await desktop.getByRole('button',{name:'Consectetur adipiscing',exact:true}).click();
assert.equal(await desktop.locator('.service-row.expanded > div').evaluate(e=>getComputedStyle(e).opacity),'1');
assert.equal(await desktop.evaluate(()=>document.getAnimations().length),0);
await desktop.emulateMedia({reducedMotion:'no-preference'});
await desktop.getByRole('button',{name:'Sed do eiusmod',exact:true}).click();
assert.ok(await desktop.locator('.service-row.expanded > div').evaluate(e=>e.getAnimations().length>0));
await desktop.waitForTimeout(250);
await desktop.goto('http://localhost:3000/catalogo');await desktop.waitForLoadState('networkidle');
const card=desktop.locator('.catalogue-card').first();await card.hover();await desktop.waitForTimeout(250);
assert.notEqual(await card.locator('img').evaluate(e=>getComputedStyle(e).transform),'none');
await desktop.screenshot({path:'.impeccable/review/motion-catalogue.png',fullPage:true});
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'no-preference'});
mobile.on('pageerror',e=>errors.push(e.message));
await mobile.goto('http://localhost:3000');await mobile.waitForLoadState('networkidle');
assert.equal(await mobile.locator('#navigation').evaluate(e=>e.inert),true);
await mobile.getByRole('button',{name:'Abrir menu'}).tap();
assert.equal(await mobile.locator('#navigation').evaluate(e=>e.inert),false);
await mobile.waitForTimeout(220);
await mobile.screenshot({path:'.impeccable/review/motion-mobile-menu.png'});
await mobile.getByRole('button',{name:'Fechar menu'}).tap();
assert.equal(await mobile.locator('#navigation').evaluate(e=>e.inert),true);
await mobile.waitForTimeout(180);
assert.equal(await mobile.locator('#navigation').evaluate(e=>getComputedStyle(e).visibility),'hidden');
await mobile.getByRole('button',{name:'Abrir menu'}).tap();
await mobile.keyboard.press('Escape');
assert.equal(await mobile.locator('#navigation').evaluate(e=>getComputedStyle(e).visibility),'hidden');
await mobile.locator('.depth-gallery').scrollIntoViewIfNeeded();
await mobile.getByRole('button',{name:'Seguinte',exact:true}).tap();
await mobile.waitForTimeout(300);
assert.equal(await mobile.locator('.depth-main').evaluate(e=>getComputedStyle(e).transform),'none','Touch has no sticky hover');
await mobile.emulateMedia({reducedMotion:'reduce'});
await mobile.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
await mobile.getByRole('button',{name:'Seguinte',exact:true}).tap();
assert.equal(await mobile.evaluate(()=>document.getAnimations().length),0);
assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await mobile.evaluate(()=>window.scrollTo(0,0));
await mobile.screenshot({path:'.impeccable/review/motion-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);
await browser.close();
console.log('PASS: pointer gallery, sampled midpoint, rapid reversal, keyboard instant, live reduced-motion, accordion, hover, mobile menu/inert/Escape and no overflow.');
