import { chromium } from 'playwright';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const route of ['/','/servicos','/empresa','/catalogo','/contactos','/admin']){await page.goto('http://localhost:3000'+route);await page.waitForLoadState('networkidle');assert.equal(await page.locator('h1').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);console.log('Route OK:',route);if(route==='/')await page.screenshot({path:'.impeccable/review/desktop.png',fullPage:true});}
await page.goto('http://localhost:3000/catalogo');await page.getByRole('button',{name:/Produtos/}).click();await page.waitForTimeout(150);assert.equal(await page.locator('.catalogue-card').count(),3);await page.getByRole('textbox',{name:'Pesquisar no catálogo'}).fill('no-match-at-all');await page.getByText('Sem resultados.').waitFor();
const credentials=readFileSync('data/acesso-local.txt','utf8');const password=credentials.match(/Palavra-passe: (.+)/)[1].trim();
await page.goto('http://localhost:3000/admin');await page.getByLabel('Utilizador',{exact:true}).fill('admin');await page.getByLabel('Palavra-passe',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.getByRole('button',{name:'Nova entrada'}).waitFor();
await page.getByRole('button',{name:'Nova entrada'}).click();await page.getByLabel('Título',{exact:true}).fill('Teste verificação');await page.getByLabel('Material',{exact:true}).fill('Mármore');await page.getByLabel('Descrição',{exact:true}).fill('Conteúdo temporário de verificação');await page.getByRole('button',{name:'Guardar alterações'}).click();await page.getByRole('button',{name:'Editar Teste verificação',exact:true}).click();await page.getByLabel('Publicado no catálogo').uncheck();await page.getByRole('button',{name:'Guardar alterações'}).click();await page.getByRole('button',{name:'Eliminar Teste verificação',exact:true}).click();await page.getByRole('button',{name:'Eliminar',exact:true}).click();await page.getByText('Entrada eliminada.').waitFor();await page.screenshot({path:'.impeccable/review/admin.png',fullPage:true});await page.getByRole('button',{name:'Terminar sessão'}).click();await page.getByRole('button',{name:'Entrar',exact:true}).waitFor();
await page.setViewportSize({width:390,height:844});for(const route of ['/','/servicos','/empresa','/catalogo','/contactos','/admin']){await page.goto('http://localhost:3000'+route);await page.waitForLoadState('networkidle');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' mobile overflow');if(route==='/'){await page.screenshot({path:'.impeccable/review/mobile.png',fullPage:true});await page.getByRole('button',{name:'Abrir menu'}).click();await page.getByRole('navigation').getByRole('link',{name:'Catálogo'}).click();await page.getByRole('heading',{name:'Catálogo.',exact:true}).waitFor();}console.log('Mobile OK:',route)}
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: routes, filters, search, admin CRUD, logout, mobile menu, no overflow, no JS errors.');
