import React,{useState,useEffect,useRef} from 'react';
import {useI18n} from './i18n.jsx';
async function request(url,options){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json'}});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}
export default function TranslationManager({onClose}){
  const {t,refresh}=useI18n();
  const [lang,setLang]=useState('en'),[group,setGroup]=useState('site'),[entries,setEntries]=useState([]),[values,setValues]=useState({}),[automatic,setAutomatic]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false),[search,setSearch]=useState('');
  const alive=useRef(true);
  useEffect(()=>()=>{alive.current=false;},[]);
  async function load(signal){setLoading(true);setError('');try{const data=await request('/api/admin/translations?lang='+lang,{signal});if(signal?.aborted)return;setEntries(data.entries);setAutomatic(data.automatic);setValues(Object.fromEntries(data.entries.map(e=>[e.key,e.saved?.draft??e.base])));setDirty(false);}catch(e){if(!signal?.aborted)setError(e.message);}finally{if(!signal?.aborted)setLoading(false);}}
  useEffect(()=>{const controller=new AbortController();load(controller.signal);return()=>controller.abort();},[lang]);
  useEffect(()=>{const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  const confirmLeave=()=>!dirty||window.confirm(t('Existem alterações por guardar. Deseja sair?'));
  const selected=entries.filter(e=>e.group===group);
  const visible=selected.filter(e=>!search||[e.source,values[e.key]].some(v=>v?.toLocaleLowerCase().includes(search.toLocaleLowerCase())));
  async function generate(){setBusy(true);setError('');setNotice('');try{const proposals=[];for(let i=0;i<selected.length;i+=50){const result=await request('/api/admin/translations/generate',{method:'POST',body:JSON.stringify({lang,keys:selected.slice(i,i+50).map(e=>e.key)})});proposals.push(...result.entries);}if(!alive.current)return;setValues(old=>({...old,...Object.fromEntries(proposals.map(e=>[e.key,e.value]))}));setDirty(true);setNotice(t('Proposta gerada. Reveja antes de publicar.'));}catch(e){if(alive.current)setError(e.message);}finally{if(alive.current)setBusy(false);}}
  async function save(publish){setBusy(true);setError('');setNotice('');try{await request('/api/admin/translations',{method:'PUT',body:JSON.stringify({lang,publish,entries:selected.filter(e=>values[e.key]?.trim()).map(e=>({key:e.key,source:e.source,value:values[e.key]}))})});if(!alive.current)return;await load();refresh();setNotice(t(publish?'Revisão publicada.':'Rascunho guardado.'));}catch(e){if(alive.current)setError(e.message);}finally{if(alive.current)setBusy(false);}}
  const groups=[...new Map(entries.map(e=>[e.group,e.label])).entries()];
  return <section className="section admin translation-manager">
    <button className="text-link" disabled={busy} onClick={()=>{if(confirmLeave())onClose();}}>{t('Voltar à gestão')}</button>
    <div className="admin-heading"><div><span className="admin-kicker">Infinity Stone</span><h1>{t('Traduzir e rever')}</h1><p>{t('As propostas ficam em rascunho. Publique apenas depois de rever.')}</p></div></div>
    <div className="translation-filters"><label>{t('Idioma de destino')}<select value={lang} disabled={busy} onChange={e=>{if(confirmLeave()){setLang(e.target.value);setNotice('');}}}><option value="en">English</option><option value="fr">Français</option></select></label><label>{t('Conteúdo')}<select value={group} disabled={busy||loading} onChange={e=>{if(confirmLeave()){setGroup(e.target.value);setValues(Object.fromEntries(entries.map(row=>[row.key,row.saved?.draft??row.base])));setDirty(false);setNotice('');setSearch('');}}}>{groups.map(([key,label])=><option key={key} value={key}>{key==='site'?t(label):label}</option>)}</select></label><label>{t('Pesquisar texto')}<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
    {!automatic&&!loading&&<p className="translation-help">{t('Os textos do site já têm tradução de base. Para gerar propostas de projetos, configure DEEPL_API_KEY no servidor.')}</p>}
    <div className="translation-actions"><button className="button" disabled={busy||loading||!selected.length||(!automatic&&group!=='site')} onClick={()=>{if(!dirty||window.confirm(t('Substituir as alterações pela nova proposta?')))generate();}}>{t(busy?'A traduzir…':'Gerar proposta')}</button><button className="button secondary" disabled={busy||loading||!selected.some(e=>values[e.key]?.trim())} onClick={()=>save(false)}>{t('Guardar rascunho')}</button><button className="button" disabled={busy||loading||!selected.length||selected.some(e=>!values[e.key]?.trim())} onClick={()=>save(true)}>{t('Publicar revisão')}</button></div>
    {error&&<p role="alert" className="error">{t(error)}</p>}{notice&&<p role="status">{notice}</p>}
    {loading?<p role="status">{t('A carregar…')}</p>:<div className="translation-entries">{visible.map(e=><div className="translation-row" key={e.key}><div><span className="admin-kicker">{t('Português original')}</span><p lang="pt">{e.source}</p><small>{t(e.saved?.source&&e.saved.source!==e.source?'Original alterado — rever':e.saved?.published===values[e.key]&&e.saved.published_source===e.source?'Publicado':e.saved?'Rascunho':e.base?'Tradução de base':'Sem tradução')}</small></div><label>{t('Tradução')} · {lang.toUpperCase()}<textarea lang={lang} rows={Math.max(2,Math.min(6,Math.ceil(e.source.length/70)))} maxLength={12000} value={values[e.key]||''} disabled={busy} onChange={event=>{setValues(old=>({...old,[e.key]:event.target.value}));setDirty(true);}}/></label></div>)}</div>}
  </section>;
}
